name: Build and Publish image to Docker Hub

on:
  push:
    tags:
      - '*-dev'   # Runs when pushing tags ending in '-dev'
      - '*-prod'  # Runs when pushing tags ending in '-prod'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: get_tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image (for -dev)
        if: contains(env.IMAGE_TAG, '-dev')
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t haucoder/cyber-store-svc:${{ env.IMAGE_TAG }} .

      - name: Build Docker images (for -prod and latest)
        if: contains(env.IMAGE_TAG, '-prod')
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t haucoder/cyber-store-svc:${{ env.IMAGE_TAG }} -t haucoder/cyber-store-svc:latest .

      - name: Push image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u haucoder --password-stdin
          docker push haucoder/cyber-store-svc:${{ env.IMAGE_TAG }}

      - name: Push latest image (only for -prod)
        if: contains(env.IMAGE_TAG, '-prod')
        run: docker push haucoder/cyber-store-svc:latest